CREATE TABLE students
(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,    
last_name VARCHAR(20) NOT NULL,
first_name VARCHAR(20) NOT NULL,
isik VARCHAR(11) NOT NULL UNIQUE,
grade int NOT NULL,
email VARCHAR(20) NOT NULL,
mess VARCHAR(250)
);